--CREATE DATABASE COMPANY


--USE COMPANY


CREATE TABLE EMPLOYEES(
[NAME] nvarchar (30),
SURNAME nvarchar (40),
JOB nvarchar (30),
SALARY int
)
INSERT INTO EMPLOYEES VALUES('MARK','JACOBS','DEVELOPER',5000)
INSERT INTO EMPLOYEES VALUES('ANNA','DARK','DEVELOPER',6000)
SELECT *FROM EMPLOYEES
--SELECT EMPLOYEES ,AVG(SALARY) AS
--AVERAGE_SALARY FROM EMPLOYEES GROUP BY EMPLOYEES
SELECT AVG(salary) AS "Avg Salary"
FROM EMPLOYEES
SELECT SALARY FROM EMPLOYEES WHERE SALARY>(SELECT AVG(salary) AS "Avg Salary"
FROM EMPLOYEES)
SELECT MIN (SALARY)  FROM EMPLOYEES 
SELECT MAX (SALARY)  FROM EMPLOYEES --VERGULLE DE YAZA BILERDIK
CREATE DATABASE SCHOOL

USE SCHOOL
CREATE TABLE STUDENTS(
ID int,
[NAME] nvarchar (30),
SURNAME nvarchar (40),
AGE int,
GRADE int
)
INSERT INTO STUDENTS VALUES(1,'MARK','JACOBS',19,8)
INSERT INTO STUDENTS VALUES(2,'ANNA','DARK',20,10)
INSERT INTO STUDENTS VALUES(3,'JANE','POTTER',22,7)
SELECT *FROM STUDENTS
SELECT [NAME] +' '+  SURNAME AS "FULLNAME"  FROM STUDENTS 
SELECT AVG(GRADE) AS "Avg grade"
FROM STUDENTS
SELECT GRADE FROM STUDENTS WHERE GRADE>(SELECT AVG(GRADE) AS GRADE
FROM STUDENTS)
SELECT GRADE FROM STUDENTS WHERE GRADE<(SELECT AVG(GRADE) AS GRADE
FROM STUDENTS)
SELECT MIN(AGE) AS "MINIK TELEBE" FROM STUDENTS
SELECT MAX(AGE) AS "BOYUK TELEBE" FROM STUDENTS
SELECT* FROM STUDENTS WHERE LEN(SURNAME)=(SELECT MAX(LEN(SURNAME)) FROM STUDENTS) ;
SELECT LEN(CONCAT ([NAME],SURNAME)) FROM STUDENTS
